select *
from sales_data_sample;


--- TASK 2
--- CORE SQL QUERIES
select 
	PRODUCTLINE,
	PRODUCTCODE
from sales_data_sample
group by PRODUCTLINE, PRODUCTCODE;


----
select 
	PRODUCTLINE,
	ROUND(SUM(SALES), 2) as Total_Sales
from sales_data_sample
group by PRODUCTLINE 
order by Total_Sales DESC;

----
select 
	COUNTRY,
	AVG(ORDERNUMBER) as Average_order_by_country
from sales_data_sample
group by COUNTRY
order by COUNTRY;


---
select 
	CITY,
	COUNT(QUANTITYORDERED) as City_Order_Count
from sales_data_sample
where CITY IN ('NYC', 'Lille', 'Paris','San Francisco', 'Chatswood')
GROUP BY CITY
having COUNT(QUANTITYORDERED) > 10; 


---
---- ADVANCED SQL CONCEPTS
select 
	ORDERNUMBER,
	ORDERDATE,
	STATUS,
	ROW_NUMBER() OVER() as Row_Num
from sales_data_sample; 


---- Using denserank because rank gave the supposed duplicates same number and skipped the next
----
select 
	CONTACTLASTNAME,
	CUSTOMERNAME,
	DEALSIZE,
	PRODUCTLINE,
	SALES,
	DENSE_RANK() OVER( 
	partition by DEALSIZE
	order by SALES desc
	) as Top_Customer
from sales_data_sample;



---- Analytical Question
--- Top Performing Product
select 
	PRODUCTLINE,
	ROUND(SUM(SALES),2) as Total_Sales,
	COUNT(STATUS) as Order_Completed
from sales_data_sample
group by PRODUCTLINE;



---- CUSTOMER PURCHASING BEHAVIOUR 
---- Checking number of orders done by each customer
select 
	CUSTOMERNAME,
	SUM(ORDERNUMBER) as Order_count
from sales_data_sample 
group by CUSTOMERNAME 
order by Order_count desc;


---- Total Revenue Generated by each customer

select
	CUSTOMERNAME,
	ORDERDATE,
	ROUND(SUM(SALES), 2) as Total_Sales
from sales_data_sample
group by CUSTOMERNAME, ORDERDATE
order by Total_Sales desc;
	
	
---- Which Products do clients prefer
select 
	CUSTOMERNAME,
	PRODUCTLINE,
	COUNT(*) as Grade
from sales_data_sample
group by CUSTOMERNAME, PRODUCTLINE
ORDER by Grade DESC;